import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#loading synthetic data generated by generate_synthetic_ehr.py
print("Loading synthetic data...")
df = pd.read_csv('data/synthetic_ehr.csv')

#picking four clinical features that will be learnt by model - specifically focusing on diabetes (trying to predict)
X = df[['age', 'blood_pressure_systolic', 'blood_pressure_diastolic', 'heart_rate']].values.astype(np.float32)
y = df['has_diabetes'].astype(int).values.astype(np.int64)

#keeping 20% of data aside for testing just to measure how well the model works
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#normalising the features so theyre all on the same scale, without this blood pressure values around 120 dominate over age (around 50) and the model doesnt learn
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#split training data across 10 simulated silos (hospitals)
NUM_CLIENTS = 10
silo_size = len(X_train) // NUM_CLIENTS
silos = []
for i in range(NUM_CLIENTS):
	start = i * silo_size
	end = start + silo_size if i < NUM_CLIENTS - 1 else len(X_train)
	dataset = TensorDataset(
		torch.tensor(X_train[start:end]),
		torch.tensor(y_train[start:end])
	)
	silos.append(dataset)

#a neural network w one hidden layer - 4inputs (clinical features) > 8 hidden nodes > 2 outputs (diabetic or not)
class SimpleNet(nn.Module):
	def __init__(self):
		super().__init__()
		self.fc = nn.Sequential(
			nn.Linear(4, 8),
			nn.ReLU(),
			nn.Linear(8, 2)
		)

	def forward(self, x):
		return self.fc(x)

#extracts the current weight from model as a list of tensors
#essentially what gets shared between clients and the server instead of the RAW DATA
def get_parameters(model):
	return [val.clone().detach() for val in model.state_dict().values()]

#loads a set of weights back into a model - used to give each client the latest global model before they train locally
def set_parameters(model, parameters):
	state_dict = dict(zip(model.state_dict().keys(), parameters))
	model.load_state_dict(state_dict, strict=True)

#simulates one client training locally on their own silo of data. it then returns updated weights after training (not the data itself)
def train_client(global_params, dataset):
	"""Train one client locally and return updated parameters."""
	model = SimpleNet()
	set_parameters(model, global_params)
	optimiser = torch.optim.Adam(model.parameters(), lr=0.01)
	criterion = nn.CrossEntropyLoss()
	loader = DataLoader(dataset, batch_size=8, shuffle=True)
	model.train()
	for batch_x, batch_y in loader:
		optimiser.zero_grad()
		loss = criterion(model(batch_x), batch_y)
		loss.backward()
		optimiser.step()
	return get_parameters(model), len(dataset)

#the core federated averaging algorithm - combines all the client updates into one global model. clients with more data have a bigger influence on the result
def federated_average(all_params, all_sizes):
	"""Aggregate client updates using weighted average (FedAvg)."""
	total = sum(all_sizes)
	averaged = []
	for layer_idx in range(len(all_params[0])):
		weighted = sum(
			all_params[c][layer_idx] * (all_sizes[c] / total)
			for c in range(len(all_params))
		)
		averaged.append(weighted)
	return averaged

#tests global model on the held out test set and returns accuracy
def evaluate(model, X_test, y_test):
	from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix
	model.eval()
	with torch.no_grad():
		outputs = model(torch.tensor(X_test))
		predictions = torch.argmax(outputs, dim=1).numpy()

	#basic accuracy aka percentage of correct predictions
	accuracy = np.mean(predictions == y_test)

	#of all patients that are diabetic, how many actually were? (precision)
	precision = precision_score(y_test, predictions, zero_division=0)

	#of all patients who are diabetic, how many were noted during the training (recall)
	recall = recall_score(y_test, predictions, zero_division=0)

	#a single number balancing both precision and recall (f1 score)
	f1 = f1_score(y_test, predictions, zero_division=0)

	#confusion matrix
	cm = confusion_matrix(y_test, predictions)

	return accuracy, precision, recall, f1, cm

#initialise global model
global_model = SimpleNet()
global_params = get_parameters(global_model)

NUM_ROUNDS = 20

#the following function gets called by the web app when training button is clicked
#wrapping it in a function allows it to be triggered multiple times without issue
def run():
	global global_model, global_params

	#reset global model each time
	global_model = SimpleNet()
	global_params = get_parameters(global_model)

	print(f"\nStarting Federated Learning simulation ({NUM_CLIENTS} clients, {NUM_ROUNDS} rounds)...\n")

	for round_num in range(1, NUM_ROUNDS + 1):
		client_params = []
		client_sizes = []

		for client_id, dataset in enumerate(silos):
			params, size = train_client(global_params, dataset)
			client_params.append(params)
			client_sizes.append(size)
			print(f"  Round {round_num} | Client {client_id + 1} trained on {size} records")

		#aggregate
		global_params = federated_average(client_params, client_sizes)
		set_parameters(global_model, global_params)

		#evaluate global model
		acc, prec, rec, f1, cm = evaluate(global_model, X_test, y_test)
		print(f" Round {round_num} | Accuracy: {acc:.2%} | Recall: {rec:.2%} | F1: {f1:.2%}")
		print(f" Confusion Matrix: TN={cm[0][0]} FP={cm[0][1]} FN={cm[1][0]} TP={cm[1][1]}\n")
	print("Federated Learning simulation completed successfully.")

#this allows the file to run directly from terminal
#when imported by web app, only run() will be called 
if __name__ == '__main__':
	run()




